"""
Trader Performance vs Bitcoin Market Sentiment — Analysis
============================================================
Explores the relationship between Hyperliquid trader behavior/performance
and the Bitcoin Fear & Greed Index.

Inputs:
    - fear_greed_index.csv   (Date, Classification)
    - historical_data.csv    (Hyperliquid trade-level data)

Output:
    - merged.csv    : trade-level data joined with daily sentiment
    - daily.csv     : daily aggregated trading + sentiment metrics
    - console report of key findings
"""

import pandas as pd
import numpy as np
from scipy import stats

pd.set_option("display.width", 120)
SENTIMENT_ORDER = ["Extreme Fear", "Fear", "Neutral", "Greed", "Extreme Greed"]


def load_and_merge(trades_path: str, sentiment_path: str) -> pd.DataFrame:
    """Load both datasets and join trades to daily sentiment classification."""
    trades = pd.read_csv(trades_path)
    sentiment = pd.read_csv(sentiment_path)

    trades["date"] = pd.to_datetime(
        trades["Timestamp IST"], format="%d-%m-%Y %H:%M"
    ).dt.date
    sentiment["date"] = pd.to_datetime(sentiment["date"]).dt.date

    merged = trades.merge(
        sentiment[["date", "value", "classification"]], on="date", how="left"
    )
    match_rate = merged["classification"].notna().mean()
    print(f"Date-match rate between trades and sentiment index: {match_rate:.4%}")
    return merged


def performance_by_sentiment(merged: pd.DataFrame) -> pd.DataFrame:
    """Core performance table: avg/median/total PnL, win rate, trade size, per sentiment bucket."""
    closed = merged[merged["Closed PnL"] != 0].copy()
    closed["win"] = closed["Closed PnL"] > 0

    summary = pd.DataFrame({
        "avg_pnl": closed.groupby("classification")["Closed PnL"].mean(),
        "median_pnl": closed.groupby("classification")["Closed PnL"].median(),
        "total_pnl": closed.groupby("classification")["Closed PnL"].sum(),
        "win_rate_%": closed.groupby("classification")["win"].mean() * 100,
        "avg_trade_size_usd": merged.groupby("classification")["Size USD"].mean(),
        "trade_count": merged["classification"].value_counts(),
    }).reindex(SENTIMENT_ORDER)
    return summary


def long_short_bias(merged: pd.DataFrame, equal_weighted: bool = False) -> pd.DataFrame:
    """% of position-opening trades that are Long vs Short, by sentiment.

    equal_weighted=False -> pooled across all trades (can be dominated by high-volume accounts)
    equal_weighted=True  -> average of each account's own %Long, then averaged across accounts
                             (more representative of "typical trader" behavior)
    """
    opens = merged[merged["Direction"].isin(["Open Long", "Open Short"])].copy()
    if not equal_weighted:
        pct = pd.crosstab(opens["classification"], opens["Direction"], normalize="index") * 100
        return pct.reindex(SENTIMENT_ORDER)
    opens["is_long"] = opens["Direction"] == "Open Long"
    per_account = opens.groupby(["classification", "Account"])["is_long"].mean().reset_index()
    equal_pct = per_account.groupby("classification")["is_long"].mean().reindex(SENTIMENT_ORDER) * 100
    return equal_pct.rename("pct_long_equal_weighted")


def equal_weighted_performance(merged: pd.DataFrame) -> pd.DataFrame:
    """Per-account PnL/win-rate, averaged across accounts (avoids whale/high-volume bias)."""
    closed = merged[merged["Closed PnL"] != 0].copy()
    closed["win"] = closed["Closed PnL"] > 0
    per_acct_pnl = closed.groupby(["classification", "Account"])["Closed PnL"].mean().reset_index()
    per_acct_win = closed.groupby(["classification", "Account"])["win"].mean().reset_index()
    result = pd.DataFrame({
        "equal_weighted_avg_pnl": per_acct_pnl.groupby("classification")["Closed PnL"].mean(),
        "equal_weighted_win_rate_%": per_acct_win.groupby("classification")["win"].mean() * 100,
        "n_accounts": closed.groupby("classification")["Account"].nunique(),
    }).reindex(SENTIMENT_ORDER)
    return result


def concentration_check(merged: pd.DataFrame) -> float:
    """% of total |Closed PnL| generated by the top-3 accounts -- flags whale bias."""
    closed = merged[merged["Closed PnL"] != 0]
    by_acct = closed.groupby("Account")["Closed PnL"].sum().abs().sort_values(ascending=False)
    return by_acct.iloc[:3].sum() / by_acct.sum()


def statistical_test(merged: pd.DataFrame):
    """One-way ANOVA: is Closed PnL significantly different across sentiment regimes?"""
    closed = merged[merged["Closed PnL"] != 0]
    groups = [closed[closed["classification"] == c]["Closed PnL"].values for c in SENTIMENT_ORDER]
    f_stat, p_value = stats.f_oneway(*groups)
    return f_stat, p_value


def daily_aggregate(merged: pd.DataFrame) -> pd.DataFrame:
    """Collapse to one row per calendar day (reduces single-account/whale bias)."""
    closed = merged[merged["Closed PnL"] != 0]
    daily = merged.groupby("date").agg(
        total_pnl=("Closed PnL", "sum"),
        avg_size_usd=("Size USD", "mean"),
        trade_count=("Closed PnL", "count"),
        sentiment_value=("value", "mean"),
    ).reset_index()
    win_rate = closed.groupby("date")["Closed PnL"].apply(lambda x: (x > 0).mean())
    daily["win_rate"] = daily["date"].map(win_rate)
    return daily


if __name__ == "__main__":
    TRADES_CSV = "historical_data.csv"
    SENTIMENT_CSV = "fear_greed_index.csv"

    merged = load_and_merge(TRADES_CSV, SENTIMENT_CSV)
    merged.to_csv("merged.csv", index=False)

    print("\n=== Performance by Sentiment Regime ===")
    summary = performance_by_sentiment(merged)
    print(summary.round(2))

    print("\n=== Long vs Short Positioning (%) -- pooled ===")
    print(long_short_bias(merged).round(1))
    print("\n=== Long vs Short Positioning (%) -- equal-weighted (per account) ===")
    print(long_short_bias(merged, equal_weighted=True).round(1))

    f_stat, p_value = statistical_test(merged)
    print(f"\nANOVA on Closed PnL across sentiment regimes: F={f_stat:.2f}, p={p_value:.5f}")

    print("\n=== Robustness check: equal-weighted (per-account) performance ===")
    print(equal_weighted_performance(merged).round(2))
    top3_share = concentration_check(merged)
    print(f"\nTop-3 accounts' share of total |Closed PnL|: {top3_share:.1%}")
    if top3_share > 0.30:
        print("WARNING: high concentration -- pooled averages may be whale-driven. Prefer equal-weighted figures.")

    daily = daily_aggregate(merged)
    daily.to_csv("daily.csv", index=False)
    print("\nDaily-level correlations (sentiment value vs metric):")
    print(f"  vs Total PnL:    {daily['sentiment_value'].corr(daily['total_pnl']):.3f}")
    print(f"  vs Trade Count:  {daily['sentiment_value'].corr(daily['trade_count']):.3f}")
    print(f"  vs Win Rate:     {daily['sentiment_value'].corr(daily['win_rate']):.3f}")
